### PR TITLE
Deprecate can.isDeferred. More accurate can.isPromise.

### LINKED ISSUE #1747: Better promise detection
A browser's Promise will fail can.isPromise.  I think we should change the test to something like:

```
can.isPromise = function(obj){
  return obj && (
     ( window.Promise && (obj instanceof Promise) ) ||
    ( can.isFunction(obj.then) && can.isFunction( obj["catch"] || obj.fail )
  )
}
```

### LINKED ISSUE #2359: Stache promise support doesn't work with ES6 promises
https://canjs.com/docs/can.stache.html#section_WorkingwithPromises

The support described here for promises in stache templates appears to only apply to jQuery deferreds. ES6 promises are just treated as any other object in a template.

If this is intended the docs should be updated to reflect it. 

A test case to demonstrate: https://github.com/nlundquist/canjs-template-promise-test

Correction: this is resolved by #2247

### PR DESCRIPTION
**Pull request by nlundquist**
Resolves #1747, closes #2359

isPromise needs to explicitly reject can.List as it shouldn't be handled as a promise and the can.List promise plugin is likely to be removed in a coming release.

### CODE REVIEW

File: util/can.js [hunk 1]
```diff
@@ -15,9 +15,16 @@ steal(function () {
...
-		return obj && typeof obj.then === "function" && typeof obj.pipe === "function";
+	
+	can.isDeferred = function() {
+		can.dev.warn('can.isDeferred: this function is deprecated and will be removed in a future release. can.isPromise replaces the functionality of can.isDeferred.');
+		return can.isPromise.call(this, arguments);
+	};
+	can.isPromise = function(obj){
+		return obj && (
+			(window.Promise && (obj instanceof Promise)) ||
+			(can.isFunction(obj.then) && can.isFunction(obj.catch || obj.fail) && !(obj instanceof can.List))
```
Comment (matthewp) [inline util/can.js]: I don't think checking for catch/fail is right as this is not a required to be a Promise.  This is probably the way to do it: https://github.com/then/is-promise/blob/master/index.js

Comment (nlundquist) [inline util/can.js]: Fair enough. Looking at the diffferences to what you linked, you think I should just remove the isFunction(catch || fail)? Or should I also check if the argument is an object or function?

Comment (matthewp) [inline util/can.js]: Not sure, wondering what scenario it is a function.  Should this work with jQuery's deferreds?  If so I'd make sure that it does (think it should)

File: util/can.js [hunk 2]
```diff
@@ -15,9 +15,16 @@ steal(function () {
...
-	can.isDeferred = can.isPromise = function (obj) {
-		// Returns `true` if something looks like a deferred.
-		return obj && typeof obj.then === "function" && typeof obj.pipe === "function";
+	
+	can.isDeferred = function() {
+		can.dev.warn('can.isDeferred: this function is deprecated and will be removed in a future release. can.isPromise replaces the functionality of can.isDeferred.');
+		return can.isPromise.call(this, arguments);
+	};
+	can.isPromise = function(obj){
+		return obj && (
```
Comment (matthewp) [inline util/can.js]: Make this be `!!obj` so it returns `false` when provided `undefined`. This function should always return a boolean.

File: util/can.js [hunk 3]
```diff
@@ -15,9 +15,16 @@ steal(function () {
 	// An empty function useful for where you need a dummy callback.
 	can.k = function(){};
 
-	can.isDeferred = can.isPromise = function (obj) {
-		// Returns `true` if something looks like a deferred.
-		return obj && typeof obj.then === "function" && typeof obj.pipe === "function";
+	
+	can.isDeferred = function() {
+		can.dev.warn('can.isDeferred: this function is deprecated and will be removed in a future release. can.isPromise replaces the functionality of can.isDeferred.');
+		return can.isPromise.call(this, arguments);
```
Comment (matthewp) [inline util/can.js]: This changes the behavior of isDeferred. If it's going to be deprecated it should have the same behavior until it is removed.

File: util/can.js (hunk 1 above)
Comment (nlundquist) [inline util/can.js]: Yeah this works with jQuery deferreds.

File: util/can.js (hunk 3 above)
Comment (nlundquist) [inline util/can.js]: Totally right.

**Comment by matthewp** [comment]
@daffl should this go into major?

File: test/pluginified/2.0.5.test.js [hunk 4]
```diff
@@ -316,7 +316,7 @@ var __m1 = (function () {
 				update: function () {
 					var deferred = this.scope.attr('deferreddata'),
 						scope = this.scope;
-					if (can.isDeferred(deferred)) {
+					if (can.isPromise(deferred)) {
```
Comment (justinbmeyer) [inline test/pluginified/2.0.5.test.js]: no changes should be made in this file.  This is our legacy test.
